import { Beer } from "@/types";

export const BEERS: Beer[] = [
  {
    id: 1,
    name: "Patagonia Amber",
    brand: "Patagonia",
    description: "Una cerveza ámbar equilibrada, con notas de caramelo y un suave amargor.",
    price: 450,
    imageUrl: "/img/Patagonia Amber.webp",
    alcoholContent: 5.2,
    type: "Amber Lager",
  },
  {
    id: 2,
    name: "Quilmes Cristal",
    brand: "Quilmes",
    description: "Cerveza lager ligera y refrescante, ideal para acompañar cualquier momento.",
    price: 380,
    imageUrl: "/img/Quilmes Cristal.webp",
    alcoholContent: 4.9,
    type: "Lager",
  },
  {
    id: 3,
    name: "Andes Golden",
    brand: "Andes",
    description: "Cerveza dorada de cuerpo medio, con un equilibrado perfil de malta y lúpulo.",
    price: 420,
    imageUrl: "/img/Andes Golden.webp",
    alcoholContent: 5.0,
    type: "Golden Ale",
  },
  {
    id: 4,
    name: "IPA Tucumana",
    brand: "Cervecería Tucumana",
    description: "IPA intensa con notas cítricas y tropicales, alto amargor y aroma a lúpulo.",
    price: 520,
    imageUrl: "/img/ipa tucumana.webp",
    alcoholContent: 6.5,
    type: "IPA",
  },
  {
    id: 5,
    name: "Stout Negro",
    brand: "Patagonia",
    description: "Stout negra con cuerpo completo, notas de café y chocolate amargo.",
    price: 480,
    imageUrl: "/img/Stout Negro.webp",
    alcoholContent: 5.8,
    type: "Stout",
  },
  {
    id: 6,
    name: "Pilsen Urbana",
    brand: "Urbana",
    description: "Pilsen clásica, dorada y brillante, con un final seco y refrescante.",
    price: 400,
    imageUrl: "/img/Pilsen Urbana.webp",
    alcoholContent: 4.7,
    type: "Pilsen",
  },
  {
    id: 7,
    name: "Red Ale Norteña",
    brand: "Norteña",
    description: "Red Ale con tono rojizo, equilibrio entre maltas caramelizadas y lúpulo herbal.",
    price: 460,
    imageUrl: "/img/Red Ale Norteña.webp",
    alcoholContent: 5.5,
    type: "Red Ale",
  },
  {
    id: 8,
    name: "Witbier Tucumana",
    brand: "Tucumana Brew",
    description: "Witbier belga con cilantro y cáscara de naranja, ligera y especiada.",
    price: 440,
    imageUrl: "/img/Witbier Tucumana.webp",
    alcoholContent: 5.0,
    type: "Witbier",
  },
  {
    id: 9,
    name: "Porter Ahumada",
    brand: "Andes",
    description: "Porter ahumada con notas de madera tostada y un toque de vainilla.",
    price: 500,
    imageUrl: "/img/Porter Ahumada.webp",
    alcoholContent: 5.6,
    type: "Porter",
  },
  {
    id: 10,
    name: "Blonde Verano",
    brand: "Patagonia",
    description: "Blonde Ale refrescante, perfecta para los días calurosos de verano.",
    price: 410,
    imageUrl: "/img/Blonde Verano.webp",
    alcoholContent: 4.8,
    type: "Blonde Ale",
  },
  {
    id: 11,
    name: "Córdoba Red",
    brand: "Córdoba Craft",
    description: "Ale rojiza con cuerpo medio and un final suave y maltoso.",
    price: 430,
    imageUrl: "/img/Córdoba Red.webp",
    alcoholContent: 5.2,
    type: "Red Ale",
  },
  {
    id: 12,
    name: "Salta Blonde",
    brand: "Salta Brew",
    description: "Blonde dorada con notas de miel y un amargor sutil.",
    price: 400,
    imageUrl: "/img/Salta Blonde.webp",
    alcoholContent: 4.9,
    type: "Blonde Ale",
  },
  {
    id: 13,
    name: "Jujuy Stout",
    brand: "Jujuy Beer",
    description: "Stout cremosa con sabores a chocolate y café tostado.",
    price: 470,
    imageUrl: "/img/Jujuy Stout.webp",
    alcoholContent: 6.0,
    type: "Stout",
  },
  {
    id: 14,
    name: "Formosa IPA",
    brand: "Formosa Craft",
    description: "IPA frutal con aroma a maracuyá y pomelo.",
    price: 530,
    imageUrl: "/img/formosa ipa.jpeg",
    alcoholContent: 6.8,
    type: "IPA",
  },
  {
    id: 15,
    name: "Chaco Lager",
    brand: "Chaco Beer",
    description: "Lager clásica, suave y muy bebible.",
    price: 390,
    imageUrl: "/img/Chaco Lager.webp",
    alcoholContent: 4.6,
    type: "Lager",
  },
];
